# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  # - osx  no osx for now (travis build server doesn't work build it)
matrix:
  allow_failures:
    - os: osx
language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  # commands for linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb          ; fi
  # commands for osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/gdb; fi
script:
  # command to run unit tests
  - python setup.py test
addons:
  apt:
    packages:
      - graphviz

